### ISSUE TITLE
how to configure HTTPS

### ISSUE THREAD

**Issue by loongcaser** [mykhrd/vue-https-webpack-cli#1]
Hello, can you provide the complete code
I don't know how to configure HTTPS

**Comment by mykhrd** [comment]
Hi, this repository is supported only with older version of vue-cli (v2.1.0). If you are going to use https with the latest vue-cli,  just add `https: true` in your webpack.dev.conf.js file.

https://webpack.js.org/configuration/dev-server/#devserver-https
